#!/bin/bash

retval=0

#set p=`dirname $0`
cwd=`pwd`"/."
p=`dirname $cwd`
source $p/_dbsettings
if [ $? != 0 ]; then
	echo "ERROR: no _dbsettings file. Are you calling from the wrong directory?"
	exit 1
fi

while [ "`echo $1 | cut -c 1`" == "-" ]; do
    if [ "$1" == "-h" || "$1" == "--help" ]; then
        goto DisplayOptions
    fi
    shift
done

# Overwrite due to command line arguments
if [ $# == 0 ]; then
    a=1

elif [ $# == 2  ]; then
    ENVIRONMENT=$1
    DBVER=$2
    DBNAME=$(ComputeDBName $APPNAME $ENVIRONMENT $DBVER)
else 
    goto ErrorOut
fi


echo ""
echo "Joining MySQL database '$DBNAME'"
echo ""
mysql --defaults-file=./.my.cnf $DBNAME
set retval=$?
exit $retval



ErrorOut:
    set retval=1
    echo "ERROR: bad command line arguments"
    echo "   $*"
DisplayOptions:
    echo 
    echo "Usage: "`basename $0`" (-h|--help) {[environment] [version]}"
    echo
    echo "   Starts mysql's client with the appropriate database."
    echo 
    echo "   environment - 'dev','test','live'"
    echo "           ver - The database version number."
    echo
exit $retval
