#!/bin/bash

retval=0
QUIET=0

function ErrorOut 
{
    set retval=1
    echo "ERROR: bad command line arguments"
    echo "   $*"
    DisplayOptions2
}
function DisplayOptions2
{
    echo 
    echo "Usage: "`basename $0`" (-h|--help) {[environment] [version]} {msqlargs}"
    echo "Usage: "`basename $0`" (-h|--help) cmd [msqlargs]"
    echo
    echo "   Starts mysql's client with the appropriate database."
    echo 
    echo "   environment - 'dev','test','live'"
    echo "           ver - The database version number."
    echo
    exit $retval
}

#set pp=`dirname $0`
#cwd=`pwd`"/."
#p=`dirname $cwd`
#source $p/config.conf
#source /usr/local/bin/db_config.conf
#if [ $? != 0 ]; then
#	echo "ERROR: no _dbsettings file. Are you calling from the wrong directory?"
#	exit 1
#fi

# NOTE: command line params are passed in here
. db_config

while [ "`echo $1 | cut -c 1`" == "-" ]; do
    echo "cmd $1"
    if [ "$1" == "-q" || "$1" == "--quite" ]; then
        QUIET=1
        echo "silent"
    elif [ "$1" == "-h" || "$1" == "--help" ]; then
        DisplayOptions2
    fi
    shift
done


# preserve cmds to mysql
if [ "$1" == "cmd" ]; then
        shift

# just start
elif [ $# == 0 ]; then
    a=1

elif [ $# -ge 2  ]; then
# Overwrite due to command line arguments
    DB_CONFIG_ENVIRONMENT=$1
    DB_CONFIG_VER=$2
    DB_CONFIG_NAME=$(ComputeDBName $DB_CONFIG_APPNAME $DB_CONFIG_SYS $DB_CONFIG_ENVIRONMENT $OLDDBVER)
    shift
    shift

else 
    ErrorOut
fi


if [ "$QUITE" == "0" ]; then
    echo ""
    echo "Joining MySQL database '$DB_CONFIG_DBNAME'"
    echo ""
fi

#echo "cmd: mysql --defaults-file=$DB_CONFIG_MYSQLMY $DB_CONFIG_DBNAME -N -B $*"
if [ $# -gt 0 ]; then
    mysql --defaults-file=$DB_CONFIG_MYSQLMY $DB_CONFIG_DBNAME -N -B "$*"
else
    mysql --defaults-file=$DB_CONFIG_MYSQLMY $DB_CONFIG_DBNAME
fi
set retval=$?
exit $retval



